server:
  port: 9191

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  allowed:
    resources: /h2-console/**
  security:
    basic:
      enabled: true
      authorize-mode: NONE
logging.level.org.springframework.web: DEBUG