server:
  port: 8080
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/expenseDB?createDatabaseIfNotExist=true
#    username: root
#    password: 1qazxsw2#
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: none
security:
  oath2:
    resource:
      token-info-uri: http://localhost:9191/oath/check_token
      client-id: web
      client-secret: pin

  spring:
    datasource:
      url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
    h2:
      console:
        enabled: true

    security:
      user:
        name: user
        password: password

